version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: MyDriversDB
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    command: --local-infile=1
    volumes:
      - ./db_setup.sql:/docker-entrypoint-initdb.d/db_setup.sql
      - ./mydrivers.csv:/mydrivers.csv
